- hosts: localhost
  become: True
  tasks:

    ## Desktop tools

    - name: Installing libselinux Python binding
      dnf:
        name: libselinux-python
        state: present

    ## Desktop tools

    - name: Installing Vim
      dnf:
        name: vim
        state: present

    - name: Installing Chrome
      dnf:
        name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present

    ## Dev tools

    - name: Create 'opt' directory
      become_user: hekonsek
      file: path=/home/hekonsek/opt state=directory

    - name: Download IntelliJ Idea
      become_user: hekonsek
      get_url:
        url: https://download-cf.jetbrains.com/idea/ideaIC-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/ideaIC-2018.1.1.tar.gz

    - name: Install IntelliJ Idea
      unarchive:
        src: /home/hekonsek/opt/ideaIC-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/

    - name: Download GoLand
      become_user: hekonsek
      get_url:
        url: https://download.jetbrains.com/go/goland-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/goland-2018.1.1.tar.gz

    - name: Install GoLand
      unarchive:
        src: /home/hekonsek/opt/goland-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/

    ## Workspace

    - name: Create 'projects' directory
      become_user: hekonsek
      file: path=/home/hekonsek/projects state=directory

    ## Containers

    - name: Installing Docker
      dnf:
        name: docker
        state: present

    - name: Make sure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes
     
    - name: Create 'docker' user group
      group:
        name: docker
        state: present

    - name: Add user 'hekonsek' to group 'docker'
      user: name=hekonsek groups=docker append=yes

    - name: Installing kubectl
      dnf:
        name: kubernetes-client
        state: present
    
