- hosts: localhost
  become: True
  tasks:

    ## Ansible

    - name: Installing libselinux Python binding
      dnf:
        name: libselinux-python
        state: present

    - name: Disable SSH host checking for Ansible
      lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: '^host_key_checking = False$'
        line: 'host_key_checking = False'
        state: present
      become: yes

    ## Desktop tools

    - name: Installing Vim
      dnf:
        name: vim
        state: present

    - name: Installing Chrome
      dnf:
        name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present

    - name: Installing Skype
      dnf:
        name: https://repo.skype.com/latest/skypeforlinux-64.rpm
        state: present

    ## Dev tools

    - name: Create 'opt' directory
      become_user: hekonsek
      file: path=/home/hekonsek/opt state=directory

    ## Java

    - name: Installing JDK
      dnf:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Installing Maven
      dnf:
        name: maven
        state: present

    - name: Download IntelliJ Idea
      become_user: hekonsek
      get_url:
        url: https://download-cf.jetbrains.com/idea/ideaIC-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/ideaIC-2018.1.1.tar.gz

    - name: Checking if IntelliJ Idea is installed
      stat: path=/home/hekonsek/opt/idea-IC-181.4445.78
      register: idea

    - name: Install IntelliJ Idea
      become_user: hekonsek
      unarchive:
        src: /home/hekonsek/opt/ideaIC-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/
      when: idea.stat.exists == False

    ## GoLang

    - name: Installing GoLang
      dnf:
        name: golang
        state: present

    - name: Download GoLand
      become_user: hekonsek
      get_url:
        url: https://download.jetbrains.com/go/goland-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/goland-2018.1.1.tar.gz

    - stat: path=/home/hekonsek/opt/GoLand-2018.1.1
      register: goland

    - name: Install GoLand
      become_user: hekonsek
      unarchive:
        src: /home/hekonsek/opt/goland-2018.1.1.tar.gz
        dest: /home/hekonsek/opt/
      when: goland.stat.exists == False

    ## Workspace

    - name: Create 'projects' directory
      become_user: hekonsek
      file: path=/home/hekonsek/projects state=directory

    ### GoLang workspace

    - name: Create GoPath directory
      become_user: hekonsek
      file: path=/home/hekonsek/projects/go state=directory

    - name: Add GoPath to PATH
      lineinfile:
        path: /home/hekonsek/.bashrc
        regexp: '^export GOPATH=/home/hekonsek/projects/go$'
        line: 'export GOPATH=/home/hekonsek/projects/go'
        state: present

    - name: Add GoPath bin to PATH
      lineinfile:
        path: /home/hekonsek/.bashrc
        regexp: '^export PATH=\$PATH:/home/hekonsek/projects/go/bin$'
        line: 'export PATH=$PATH:/home/hekonsek/projects/go/bin'
        state: present

    ## Containers

    - name: Installing Docker
      dnf:
        name: docker
        state: present

    - name: Make sure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes
     
    - name: Create 'docker' user group
      group:
        name: docker
        state: present

    - name: Add user 'hekonsek' to group 'docker'
      user: name=hekonsek groups=docker append=yes

    - name: Installing kubectl
      dnf:
        name: kubernetes-client
        state: present
    
