- hosts: localhost
  become: True
  tasks:

    ## Desktop tools

    - name: Installing Vim
      dnf:
        name: vim
        state: present

    - name: Installing Chrome
      dnf:
        name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present

    ## Workspace

    - name: Create 'projects' directory
      become_user: hekonsek
      file: path=/home/hekonsek/projects state=directory

    ## Containers

    - name: Installing Docker
      dnf:
        name: docker
        state: present

    - name: Make sure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes
     
    - name: Create 'docker' user group
      group:
        name: docker
        state: present

    - name: Add user 'hekonsek' to group 'docker'
      user: name=hekonsek groups=docker append=yes

    - name: Installing kubectl
      dnf:
        name: kubernetes-client
        state: present
    
    - name: Install Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/v0.26.1/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: 0555
        checksum: md5:8fb2128d23cd8d1b1f28c791804f791f
